default: &default
  adapter: postgresql
  password: <%= Rails.application.credentials.dig(:database, :development) %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bestclip_development
  username: bestclip
  host: localhost
  port: 5432
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

test:
  <<: *default
  database: bestclip_test


production:
  <<: *default
  database: bestclip_production
  username: bestclip
  password: <%= Rails.application.credentials.dig(:database, :production) %>
